name: Deploy Images to GHCR

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
      build-and-push:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
              
          - name: Set env
            id: vars
            run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

          - name: echo 
            run: echo ${{ steps.vars.outputs.tag }}
            
          - name: build image
            run: |
              docker build . -t ghcr.io/simbafs/coscup-attendance:latest -t ghcr.io/simbafs/coscup-attendance:${{ steps.vars.outputs.tag }}

          - name: push image
            run: |
              docker push ghcr.io/simbafs/coscup-attendance:${{ steps.vars.outputs.tag }}
              docker push ghcr.io/simbafs/coscup-attendance:latest


      cd:
        runs-on: ubuntu-latest
        needs: [build-and-push]
        steps:
          - name: trigger webhook
            run: |
              curl -XPOST --header 'Content-Type: application/json'  -d'{"key": "${{ secrets.WEBHOOK_KEY }} "}' "https://webhook.simbafs.cc/hooks/coscup-attendance"
